### PR TITLE
CI: Build/upload to conda

### LINKED ISSUE #8: Make this a python package installable via conda
We should be able to put this into the pcds_conda environment and be able to run it whenever we want

### PR DESCRIPTION
**Pull request by ZLLentz**
So I can put this in the pcds conda and then we can be one step closer to tag/build/deploy scripts for IOCs, etc.

closes #8

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Nice that our scripts are configurable enough for this 👍 

Would you mind also adding the PyPI step? I added it there and will add a token to this repo for automatic uploads as well.

**Comment by ZLLentz** [comment]
Yes I will add the pypi upload step.
I just finished adding the anaconda tokens.

**Comment by klauer** [comment]
Perfect. PyPI token added as well 👍

**Comment by ZLLentz** [comment]
Installing the pcds-dev channel package definitely worked :+1:

**Pull request merged**
